import React from "react";
import { darken, lighten } from "polished";
import { Fonts, Colors } from "../../theme/theme";
import { withStyles, ListItem, Menu, MenuItem } from "@material-ui/core";

export const drawerWidth = 180;
const drawerCloseWidth = 200;
const smallDrawerCloseWidth = 40;
const smallDrawerOpenWidth = 120;

export const StyledListItem = withStyles({
  root: {
    backgroundColor: Colors.light,
    fontSize: Fonts.font,
    "&$selected": {
      backgroundColor: "transparent",
      color: Colors.blue,
      borderLeft: `4px solid ${Colors.blue}`,
      borderRadius: 4,
      "&:focused": {
        backgroundColor: "transparent",
        color: Colors.blue,
        borderLeft: `4px solid ${Colors.blue}`,
        borderRadius: 4,
      },
      "&:hover": {
        backgroundColor: "transparent",
        color: Colors.blue,
        borderLeft: `4px solid ${Colors.blue}`,
        borderRadius: 4,
      },
      "& .MuiListItemIcon-root, & .MuiListItemText-primary": {
        color: Colors.blue,
      },
      "& .MuiListItem-gutters": {
        paddingLeft: 10,
        paddingRight: 16,
      },
    },
  },
  selected: {},
})(ListItem);

export const StyledMenu = withStyles({
  paper: {
    // width: 244
    "& .MuiList-padding": {
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
})((props) => (
  <Menu
    elevation={0}
    getContentAnchorEl={null}
    anchorOrigin={{
      vertical: "bottom",
      horizontal: "center",
    }}
    transformOrigin={{
      vertical: "top",
      horizontal: "center",
    }}
    {...props}
  />
));

export const StyledMenuItem = withStyles(() => ({
  root: {
    "&$selected": {
      backgroundColor: "transparent",
      color: Colors.blue,
      borderLeft: `4px solid ${Colors.blue}`,
      borderRadius: 4,
      "&:hover": {
        backgroundColor: "transparent",
        color: Colors.blue,
        borderLeft: `4px solid ${Colors.blue}`,
        borderRadius: 4,
      },
      "&:focus": {
        backgroundColor: "transparent",
        color: Colors.blue,
        borderRadius: 4,
        "& .MuiListItemIcon-root, & .MuiListItemText-primary": {
          color: Colors.blue,
        },
      },
    },
  },
}))(MenuItem);

export const styles = (theme) => ({
  root: {
    display: "flex",
    fontFamily: Fonts.primary,
    fontSize: Fonts.font,
  },
  appBar: {
    [theme.breakpoints.up("sm")]: {
      maxHeight: 50,
    },
    height: 50,
  },
  appBarShift: {
    [theme.breakpoints.up("sm")]: {
      marginLeft: drawerWidth,
      backgroundColor: Colors.light,

      width: `calc(100% - ${drawerWidth}px)`,
      boxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 1px 1px 0px",
    },
    marginLeft: smallDrawerOpenWidth,
    width: `calc(100% - ${smallDrawerOpenWidth}px)`,
    backgroundColor: Colors.light,
    boxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 1px 1px 0px",
  },
  appbarNormal: {
    [theme.breakpoints.up("sm")]: {
      marginLeft: drawerCloseWidth,
      backgroundColor: Colors.light,
      width: `calc(100% - ${drawerCloseWidth}px)`,
      boxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 1px 1px 0px",
    },
    marginLeft: smallDrawerCloseWidth,
    backgroundColor: Colors.light,
    width: `calc(100% - ${smallDrawerCloseWidth}px)`,
    boxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 1px 1px 0px",
  },
  mailIcon: {
    color: Colors.menuListColor,
    marginTop: 3,
  },
  notificationIcon: {
    display: "flex",
    float: "right",
    position: "absolute",
    top: -21,
    left: -10,
  },
  paper: {
    width: "auto",
    height: "auto",
    borderRadius: 0,
    marginLeft: -60,
    marginTop: 29,
    FontFamily: Fonts.primary,
    FontSize: Fonts.font,
    backgroundColor: Colors.light,
    WebkitBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    MozBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    boxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    "&:hover": {
      backgroundColor: Colors.light,
    },
    "&:focus": {
      backgroundColor: Colors.light,
    },
  },
  menuItemRoot: {
    marginLeft: 10,
    marginRight: 10,
    FontFamily: Fonts.primary,
    FontSize: Fonts.font,
    padding: 4,
    backgroundColor: Colors.light,
    "&:hover": {
      backgroundColor: Colors.light,
    },
    "&:focus": {
      backgroundColor: Colors.light,
    },
  },
  notificationMenuList: {
    textTransform: "initial",
    fontSize: Fonts.font,
    fontFamily: Fonts.primary,
  },
  drawer: {
    width: drawerWidth,
    flexShrink: 0,
    whiteSpace: "nowrap",
    color: "#fff",
  },
  drawerOpen: {
    [theme.breakpoints.up("sm")]: {
      width: drawerWidth,
      backgroundColor: Colors.light,
      overflowX: "hidden",
      transition:
        "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
    },
    width: smallDrawerOpenWidth,
    backgroundColor: Colors.light,
    overflowX: "hidden",
    transition:
      "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
  },
  drawerClose: {
    [theme.breakpoints.up("sm")]: {
      width: drawerCloseWidth,
      backgroundColor: Colors.light,
      transition:
        "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
      overflowX: "hidden",
    },
    transition:
      "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
    overflowX: "hidden",
    width: smallDrawerCloseWidth,
    backgroundColor: Colors.light,
  },
  grow: {
    [theme.breakpoints.up("sm")]: {
      flexGrow: 1,
    },
    flexGrow: 1,
  },
  toolbar: {
    [theme.breakpoints.up("sm")]: {
      display: "flex",
      alignItems: "center",
      justifyContent: "flex-end",
      padding: "0 8px",
      ...theme.mixins.toolbar,
    },
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: "0 8px",
    ...theme.mixins.toolbar,
  },
  ToolbarRoot: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    padding: "0 8px",
  },
  appnameLogo: {
    [theme.breakpoints.up("sm")]: {
      position: "relative",
      top: 0,
      bottom: 0,
      height: 50,
      width: 140,
      margin: "0 auto",
      marginLeft: 4,
      marginBottom: 0,
      borderBottom: "1px solid #eee",
    },
    position: "relative",
    top: 0,
    bottom: 0,
    height: 50,
    marginBottom: 0,
    borderBottom: "1px solid #eee",
  },
  menuIcon: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      cursor: "pointer",
      top: 15,
      left: 18,
      fontSize: 25,
      color: Colors.menuListColor,
    },
    position: "absolute",
    cursor: "pointer",
    top: 8,
    left: 8,
    fontSize: 20,
    color: Colors.menuListColor,
  },
  appName: {
    [theme.breakpoints.up("sm")]: {
      color: Colors.blue,
      fontSize: Fonts.font,
      marginLeft: 52,
      position: "relative",
      top: 18,
      left: 2,
      cursor: "pointer",
      fontWeight: 500,
    },
    color: Colors.blue,
    fontSize: Fonts.font,
    position: "relative",
    top: 16,
    left: 40,
    fontWeight: 500,
  },
  appIconStyle: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      top: 18,
      left: 18,
      fontSize: 18,
      color: Colors.blue,
    },
    position: "absolute",
    top: 13,
    left: 8,
    fontSize: 18,
    color: Colors.blue,
  },
  companyButton: {
    [theme.breakpoints.up("sm")]: {
      fontSize: 25,
      outline: "none",
      cursor: "pointer",
    },
    fontSize: 20,
  },
  appSwitchArrowBtnSelfService: {
    [theme.breakpoints.up("sm")]: {
      padding: 0,
      position: "absolute",
      left: 116,
      top: 11,
      bottom: 0,
      cursor: "pointer",
      color: Colors.menuListColor,
      "&:hover": {
        backgroundColor: "transparent",
      },
      "&:focus": {
        backgroundColor: "transparent",
      },
    },
    position: "relative",
    left: 90,
    top: 12,
    bottom: 0,
    color: Colors.menuListColor,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "transparent",
    },
    "&:focus": {
      backgroundColor: "transparent",
    },
  },
  appSwitchArrowBtn: {
    [theme.breakpoints.up("sm")]: {
      padding: 0,
      position: "absolute",
      left: 100,
      top: 11,
      bottom: 0,
      cursor: "pointer",
      color: Colors.menuListColor,
      "&:hover": {
        backgroundColor: "transparent",
      },
      "&:focus": {
        backgroundColor: "transparent",
      },
    },
    position: "relative",
    left: 90,
    top: 12,
    bottom: 0,
    color: Colors.menuListColor,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "transparent",
    },
    "&:focus": {
      backgroundColor: "transparent",
    },
  },
  appSwitchMenu: {
    [theme.breakpoints.up("sm")]: {
      zIndex: 1000000,
      width: `calc(${drawerWidth}px - 1.5px)`,
      marginTop: 39,
      paddingTop: 0,
      paddingBottom: 0,
      borderRadius: 0,
      fontSize: Fonts.font,
      position: "initial",
      color: Colors.menuListColor,
      WebkitBoxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      MozBoxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      boxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      borderBottomLeftRadius: 5,
      borderBottomRightRadius: 5,
      backgroundColor: Colors.light,
      borderBottom: `1px solid ${lighten(0.4, Colors.grey)}`,
    },
    zIndex: 10000,
    fontSize: Fonts.font,
    width: `calc(${smallDrawerOpenWidth}px - 5px)`,
    marginTop: 40,
    paddingTop: 0,
    paddingBottom: 0,
    borderRadius: 0,
    position: "initial",
    color: Colors.menuListColor,
    WebkitBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    MozBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    boxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    backgroundColor: Colors.light,
  },
  menuItem: {
    [theme.breakpoints.up("sm")]: {
      fontSize: Fonts.font,
      color: Colors.menuListColor,
      marginLeft: 9,
      fontFamily: Fonts.primary,
      textTransform: "none",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      "&:hover": {
        marginLeft: 10,
        color: Colors.menuListColor,
        borderLeft: `3px solid ${Colors.blueSecondary}`,
      },
      "&:focus": {
        marginLeft: 9,
        borderLeft: `3px solid ${Colors.blueSecondary}`,
        color: Colors.menuListColor,
      },
    },
    fontSize: Fonts.font,
    color: Colors.menuListColor,
    marginLeft: 5,
    fontFamily: Fonts.primary,
    textTransform: "none",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    "&:hover": {
      color: Colors.menuListColor,
      borderLeft: `1.5px solid ${Colors.blueSecondary}`,
    },
    "&:focus": {
      color: Colors.menuListColor,
    },
  },
  menuListIcons: {
    [theme.breakpoints.up("sm")]: {
      color: Colors.menuListColor,
      marginRight: 10,
      marginLeft: 0,
    },
    color: Colors.menuListColor,
    marginRight: 10,
    marginLeft: 0,
  },

  fab: {
    [theme.breakpoints.up("sm")]: {
      zIndex: 10000,
      boxShadow: "none",
      color: "#fff",
      cursor: "pointer",
      lineHeight: 14,
      minHeight: 10,
      minWidth: 10,
      height: 20,
      width: 20,
      opacity: 1,
      position: "fixed",
      top: 100,
      left: `calc(1px + ${drawerWidth}px)`,
      transform: "translate(-50%)",
      display: "flex",
      justifyContent: "center",
      background: Colors.blue,
      borderWidth: 0,
      borderStyle: "initial",
      borderColor: "initial",
      borderImage: "initial",
      borderRadius: "50%",
      padding: 0,
      transition:
        "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
      "&:hover": {
        backgroundColor: Colors.light,
        color: Colors.blue,
      },
      "&:focus": {
        backgroundColor: Colors.light,
        color: Colors.blue,
      },
    },
    zIndex: 10000,
    boxShadow: "none",
    color: "#fff",
    cursor: "pointer",
    lineHeight: 14,
    minHeight: 10,
    minWidth: 10,
    height: 20,
    width: 20,
    opacity: 1,
    position: "fixed",
    top: 60,
    left: `calc(2px + ${smallDrawerOpenWidth}px)`,
    transform: "translate(-50%)",
    display: "flex",
    justifyContent: "center",
    background: Colors.blue,
    borderWidth: 0,
    borderStyle: "initial",
    borderColor: "initial",
    borderImage: "initial",
    borderRadius: "50%",
    padding: 0,
    transition:
      "background-color 100ms linear 0s, color 100ms linear 0s, opacity 300ms cubic-bezier(0.2, 0, 0, 1) 0s, transform 300ms cubic-bezier(0.2, 0, 0, 1) 0s",
    "&:hover": {
      backgroundColor: Colors.light,
      color: Colors.blue,
    },
    "&:focus": {
      backgroundColor: Colors.light,
      color: Colors.blue,
    },
  },

  listRoot: {
    [theme.breakpoints.up("sm")]: {
      width: "100%",
      maxWidth: `calc(${drawerWidth}px - 20px)`,
      backgroundColor: Colors.light,
      margin: "0 auto",
    },
    width: "100%",
    maxWidth: `calc(${smallDrawerOpenWidth}px - 10px)`,
    backgroundColor: Colors.light,
  },
  nested: {
    [theme.breakpoints.up("sm")]: {
      cursor: "pointer",
    },
    cursor: "pointer",
  },
  listChildren: {
    [theme.breakpoints.up("sm")]: {
      position: "relative",
      left: 30,
      width: 154,
      fontFamily: Fonts.primary,
      textTransform: "none",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    position: "relative",
    left: 10,
  },
  sidebarListItem: {
    [theme.breakpoints.up("sm")]: {
      cursor: "pointer",
    },
    cursor: "pointer",
  },
  listItemIcon: {
    [theme.breakpoints.up("sm")]: {
      color: Colors.menuListolor,
      // minWidth: 20,
      // width: 30,
    },
    color: Colors.menuListColor,
    margin: 0,
    // minWidth: 20,
    // width: 20,
  },

  sidebarText: {
    [theme.breakpoints.up("sm")]: {
      color: Colors.menuListColor,
      fontSize: Fonts.font,
      // // fontWeight: 500,
      // width: 120,
      fontFamily: Fonts.primary,
      // textTransform: "none",
      // whiteSpace: "nowrap",
      // overflow: "hidden",
      // textOverflow: "ellipsis",
      marginLeft: -18,
    },
    color: Colors.menuListColor,
    fontSize: Fonts.font,
    fontFamily: Fonts.primary,
    // fontWeight: 500,
    // width: smallDrawerOpenWidth,
    // textTransform: "none",
    // whiteSpace: "nowrap",
    // overflow: "hidden",
    // textOverflow: "ellipsis",
  },
  sidebarNestedText: {
    [theme.breakpoints.up("sm")]: {
      // color: Colors.menuListColor,
      fontSize: Fonts.font,
      // fontWeight: 500,
      width: 100,
      position: "relative",
      left: -18,
      fontFamily: Fonts.primary,
      // textTransform: "none",
      // whiteSpace: "nowrap",
      // overflow: "hidden",
      // textOverflow: "ellipsis",
    },
    // color: Colors.menuListColor,
    fontSize: Fonts.font,
    width: 50,
    fontFamily: Fonts.primary,
    position: "relative",
    left: -25,
    // fontWeight: 500,
    // textTransform: "none",
    // whiteSpace: "nowrap",
    // overflow: "hidden",
    // textOverflow: "ellipsis",
  },
  nestedIcon: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      right: 0,
      left: 135,
      color: "inherit",
    },
    position: "absolute",
    right: 0,
    left: 48,
    color: Colors.menuListColor,
  },
  sideBarLoader: {
    [theme.breakpoints.up("sm")]: {
      color: Colors.blue,
      marginTop: "30vh",
      marginLeft: drawerWidth / 2 - 20,
      transition: theme.transitions.create("all", {
        easing: theme.transitions.easing.sharp,
        duration: theme.transitions.duration.enteringScreen,
      }),
    },
    color: Colors.blue,
    marginTop: "30vh",
    marginLeft: drawerWidth / 2 - 20,
    transition: theme.transitions.create("all", {
      easing: theme.transitions.easing.sharp,
      duration: theme.transitions.duration.enteringScreen,
    }),
  },
  sideBarErrorText: {
    [theme.breakpoints.up("sm")]: {
      fontFamily: Fonts.primary,
      marginTop: 30,
      marginLeft: 30,
      fontSize: Fonts.font,
      width: drawerWidth - 20,
      color: Colors.blue,
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
    },
    fontFamily: Fonts.primary,
    marginTop: 30,
    marginLeft: 15,
    fontSize: Fonts.font,
    width: smallDrawerOpenWidth,
    color: Colors.blue,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  timeDate: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: -5,
      padding: 1,
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
      color: Colors.textColor,
    },
    position: "absolute",
    left: 5,
    padding: 1,
    fontSize: Fonts.font,
    fontFamily: Fonts.primary,
    color: Colors.textColor,
  },
  profile: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: "80%",
      padding: 1,
      cursor: "pointer",
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
      color: Colors.textColor,
    },
    position: "absolute",
    left: "80%",
    padding: 1,
    cursor: "pointer",
    fontSize: Fonts.font,
    fontFamily: Fonts.primary,
    color: Colors.textColor,
  },
  accessTimeIcon: {
    [theme.breakpoints.up("sm")]: {
      fontSize: 19,
      position: "relative",
      left: 40,
      right: 20,
      top: -9.5,
      bottom: 0,
      color: Colors.textColor,
      paddingLeft: 5,
    },
    fontSize: 15,
    position: "relative",
    left: 0,
    right: 0,
    top: -10,
    bottom: 0,
    color: Colors.textColor,
    paddingLeft: 2,
  },
  momentTime: {
    [theme.breakpoints.up("sm")]: {
      fontSize: Fonts.font,
      position: "relative",
      width: 119,
      height: 17,
      left: 45,
      top: -8,
      color: Colors.textColor,
      paddingLeft: 2,
    },
    fontSize: 9,
    position: "relative",
    left: 1,
    top: -8,
    color: Colors.textColor,
    paddingLeft: 1,
  },
  CalendarTodayIcon: {
    [theme.breakpoints.up("sm")]: {
      fontSize: 17,
      position: "relative",
      left: 70,
      right: 20,
      top: -9.4,
      bottom: 0,
      color: Colors.textColor,
      paddingLeft: 5,
    },
    fontSize: 15,
    position: "relative",
    left: 3,
    right: 0,
    top: -9,
    bottom: 0,
    color: Colors.textColor,
    paddingLeft: 2,
  },
  momentDate: {
    [theme.breakpoints.up("sm")]: {
      fontSize: Fonts.font,
      position: "relative",
      width: 119,
      height: 17,
      left: 75,
      top: -8,
      color: Colors.textColor,
      paddingLeft: 2,
    },
    fontSize: 9,
    position: "relative",
    width: 119,
    height: 17,
    left: 4,
    top: -8,
    paddingLeft: 1,
    color: Colors.textColor,
  },
  accountIconAvatar: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: 25,
      top: -12,
    },
    position: "absolute",
    left: -20,
    top: -8,
  },
  accountIconAvatarLoader: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: 60,
      top: -10,
    },
    position: "absolute",
    left: -20,
    top: -8,
  },
  accountIcon: {
    [theme.breakpoints.up("sm")]: {
      fontSize: 34,
      position: "absolute",
      left: 50,
      top: -25,
      color: darken(0.1, Colors.light),
    },
    fontSize: 22,
    position: "absolute",
    left: -49,
    top: -18,
    color: darken(0.1, Colors.light),
  },
  line2: {
    border: `0.5px solid ${Colors.greyLight}`,
    margin: 5,
  },
  profileDropdown: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: 120,
      top: -27.678,
      display: "inline-block",
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
    },
    position: "absolute",
    left: 58,
    top: -42.672,
    display: "inline-block",
    fontSize: 9,
    fontFamily: Fonts.primary,
  },
  profileTitle: {
    [theme.breakpoints.up("sm")]: {
      width: 150,
      height: 40,
      display: "flex",
      lineHeight: "0.3rem",
      marginLeft: "13%",
      marginTop: -8,
      padding: 0,
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
    },
    width: 150,
    height: 40,
    display: "flex",
    lineHeight: "0.3rem",
    marginLeft: 2,
    marginTop: 8,
    padding: 0,
    fontSize: 9,
    fontFamily: Fonts.primary,
  },
  profileName: {
    display: "inline-block",
  },
  accountName: {
    [theme.breakpoints.up("sm")]: {
      whiteSpace: "nowrap",
      width: 70,
      height: 20,
      overflow: "hidden",
      textOverflow: "ellipsis",
      color: Colors.blue,
      fontSize: Fonts.font,
      textTransform: "capitalize",
      padding: 5,
      marginLeft: -52,
      marginTop: 14,
      background: "transparent",
    },
    whiteSpace: "nowrap",
    width: 70,
    height: 20,
    overflow: "hidden",
    textOverflow: "ellipsis",
    color: Colors.blue,
    fontSize: 8,
    textTransform: "capitalize",
    padding: 5,
    marginLeft: -80,
    marginTop: 16,
    background: "transparent",
  },
  accountCompany: {
    [theme.breakpoints.up("sm")]: {
      whiteSpace: "nowrap",
      width: 110,
      height: 20,
      overflow: "hidden",
      textOverflow: "ellipsis",
      background: "transparent",
      color: "#888",
      fontSize: 12,
      padding: 5,
      marginTop: -14,
      marginLeft: -52,
    },
    whiteSpace: "nowrap",
    width: 70,
    height: 20,
    overflow: "hidden",
    textOverflow: "ellipsis",
    background: "transparent",
    color: "#888",
    fontSize: 8,
    padding: 5,
    marginTop: -16,
    marginLeft: -80,
  },
  profileButton: {
    fontSize: 25,
  },
  dropdownIcon: {
    [theme.breakpoints.up("sm")]: {
      position: "relative",
      top: -34,
      left: 9,
      marginTop: "9%",
      marginLeft: "33%",
      color: Colors.menuListColor,
    },
    [theme.breakpoints.down("sm")]: {
      display: "none",
    },
  },
  dropdownList: {
    [theme.breakpoints.up("sm")]: {
      position: "absolute",
      left: -82,
      top: 42,
      width: 175,
      height: "auto",
      background: Colors.light,
      textTransform: "capitalize",
      color: Colors.menuListColor,
      fontSize: Fonts.font,
      WebkitBoxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      MozBoxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      boxShadow:
        "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 4,
      padding: 5,
      cursor: "pointer",
    },
    position: "absolute",
    top: 42,
    left: -160,
    width: 175,
    height: "auto",
    background: Colors.light,
    textTransform: "capitalize",
    color: Colors.menuListColor,
    fontSize: Fonts.font,
    WebkitBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    MozBoxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    boxShadow:
      "rgba(9, 30, 66, 0.08) 0px 0px 0px 0px, rgba(9, 30, 66, 0.08) 0px 3px 3px 0px",
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
    padding: 5,
    cursor: "pointer",
  },
  line1: {
    [theme.breakpoints.up("sm")]: {
      border: `0.1px solid ${Colors.greyLight}`,
      margin: "2px 0 5px",
    },
    border: `0.1px solid ${Colors.greyLight}`,
    margin: "2px 0 5px",
  },
  profileDropdownActionName: {
    [theme.breakpoints.up("sm")]: {
      marginTop: 9,
      marginLeft: 8,
    },
    marginTop: 9,
    marginLeft: 8,
  },
  dropdownActionName: {
    marginTop: 5,
  },
  dropdownBusinessGroup: {
    display: "flex",
    textTransform: "capitalize",
    padding: 5,
    margin: 5,
    "&:hover": {
      background: darken(0.02, Colors.light),
    },
  },
  dropdownBusinessName: {
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    paddingTop: 5,
  },
  currentBusiness: {
    color: darken(0.2, Colors.light),
  },
  dropdownBusinessIcon: {
    marginRight: 12,
    marginLeft: 10,
    textOverflow: "ellipsis",
  },
  dropdownAction: {
    display: "flex",
    padding: 5,
    margin: 5,
    marginLeft: 0,
    color: Colors.menuListColor,
    fontSize: Fonts.font,
    "&:hover": {
      background: darken(0.02, Colors.light),
    },
  },
  dropdownActionIcon: {
    marginRight: 10,
    marginLeft: 13,
  },
  logoutDropdownAction: {
    display: "flex",
    padding: 8,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    color: Colors.buttonError,
    fontSize: 12,
    margin: -5,
    marginTop: 5,
  },
  logoutDropdownActionIcon: {
    marginRight: 10,
    marginLeft: 15,
  },
  logoutDropdownActionName: {
    marginTop: 3,
    color: Colors.buttonError,
  },
  content: {
    [theme.breakpoints.up("sm")]: {
      flexGrow: 1,
      margin: 5,
      marginLeft: 40,
      marginRight: 40,
      width: `calc(100% - ${drawerWidth}px - 40px - 30px)`,
      color: Colors.textColor,
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
    },
    [theme.breakpoints.down("sm")]: {
      marginLeft: 30,
      marginRight: 30,
      width: `calc(100% - ${smallDrawerOpenWidth}px)`,
      color: Colors.textColor,
      fontSize: Fonts.font,
      fontFamily: Fonts.primary,
    },
  },
});
